SDK_ruby/sample-project/Sample_SDK_testing/config/routes.rb
Rails.application.routes.draw do
  get 'deliveree/index'
  get 'deliveree/get_quotes'
  get 'deliveree/create_booking'
  get 'deliveree/cancel_booking'
  get '/', to: 'deliveree#index'

end

SDK_ruby/sample-project/Sample_SDK_testing/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SDK_ruby/sample-project/Sample_SDK_testing/app/controllers/deliveree_controller.rb
class DelivereeController < ApplicationController
  def index
  end

  def get_quotes
    deliveree = Deliveree::DelivereeApi.new
    location = {
      address:
        "Jl. Sultan Iskandar Muda No.21, Arteri Pondok Indah, Pd. Pinang, Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
      latitude: -6.2608232,
      longitude: 106.7884168
    }

    body = Deliveree::Quote.new({time_type: "now", locations: [Deliveree::Location.new( location)]})

    begin
      @result = deliveree.deliveries_get_quote(body)
    rescue Deliveree::ApiError => e
      @error = e
      puts "exception #{e}"
    end
  end

  def create_booking
    deliveree = Deliveree::DelivereeApi.new
    tDate = DateTime.now.to_s
    delivery = {
     vehicle_type_id: 62,
     note: "Testing - API Default Fragile item that needs good care Welcome.",
     time_type: "schedule",
     pickup_time: "2016-05-13T09:51:16+07:00",
     job_order_number: "66666",
     locations: [
       {
         address:
           tDate +
             "Jl. Sultan Iskandar Muda No.21, Arteri Pondok Indah, Pd. Pinang, Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
         latitude: -6.2608232,
         longitude: 106.7884168,
         recipient_name: "Duke",
         recipient_phone: "+84903398399",
         note: "Second floor, room 609"
       },
       {
         address:
           tDate +
             "Gedung Inti Sentra, Jl. Taman Kemang, RT.14/RW.1, Bangka, Mampang Prpt., Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
         latitude: -6.2608232,
         longitude: 106.7884168,
         recipient_name: "Nam",
         recipient_phone: "+84903856534",
         note: "First floor, right room.",
         need_cod: true,
         cod_note: "You need to get money from Nam",
         cod_invoice_fees: 5000,
         need_pod: true,
         pod_note: "You need to ..."
       }
     ]
   }
    begin
      @deliver = deliveree.deliveries_post(delivery)
      puts @deliver
    rescue Deliveree::ApiError => e
      @error = e
      puts "exception #{e}"
    end
  end

  def cancel_booking
    deliveree = Deliveree::DelivereeApi.new
    booking_id = 17463
    begin
      @result = deliveree.cancel_booking(booking_id)
      puts @result
    rescue Deliveree::ApiError => e
      puts "exception #{e}"
      @err = e
    end
  end

end

SDK_ruby/sample-project/Sample_SDK_testing/app/helpers/application_helper.rb
module ApplicationHelper
end

SDK_ruby/sample-project/Sample_SDK_testing/app/helpers/deliveree_helper.rb
module DelivereeHelper
end

SDK_ruby/sample-project/Sample_SDK_testing/app/views/deliveree/cancel_booking.html.erb
<hr/>
<div class="row">
  <div class="col-lg-12">
    <div class="header">
      <h2>
       Cancel booking delivery
      </h2>

    </div>
  </div>
  <div class="col-lg-6">
    <% if @err %>
      <div class="alert alert-warning" role="alert">
        <%=@err %>
      </div>
    <%end %>
    <% if @result %>
      <div class="alert alert-warning" role="alert">
        <%=@result %>
      </div>
    <%end %>

  </div>
  <div class="col-lg-6 code">
  <pre><code>
    deliveree = Deliveree::DelivereeApi.new
    booking_id= 10 # Id of Delivery with status is not COMPLETED or CANCELED
    begin
      deliveree.cancel_booking(booking_id) # With no return data and status
    rescue Deliveree::ApiError => e
      puts "exception #{e}"
    end
</code></pre>
  </div>

</div>

SDK_ruby/sample-project/Sample_SDK_testing/app/views/deliveree/create_booking.html.erb
<hr/>
<div class="row">
  <div class="col-lg-12">
    <div class="header">
      <h2>
        Create Booking delivery
      </h2>

    </div>
  </div>
  <div class="col-lg-6">
    <table class="table">
      <tr>
        <td>Delivery ID</td>
        <td>Customer ID</td>
        <td>Company ID</td>
        <td>Time type</td>
        <td>Note</td>
        <td>Total Fees</td>
        <td>Currency</td>
      </tr>
        <tr>
        <% if @deliver.present? %>
          <td>
            <%=@deliver.id %>
          </td>
          <td>
            <%=@deliver.customer_id %>
          </td>
          <td>
            <%=@deliver.company_id %>
          </td>
          <td>
            <%=@deliver.time_type %>
          </td>
          <td>
            <%=@deliver.note %>
          </td>
          <td>
            <%=@deliver.total_fees %>
          </td>
          <td>
            <%=@deliver.currency %>
          </td>
        <%else %>
          <td colspan="8"> <%=@error %></td>
        <%end %>

        </tr>
    </table>

  </div>
  <div class="col-lg-6 code">
  <pre><code>
    deliveree = Deliveree::DelivereeApi.new
    tDate = DateTime.now.to_s
    delivery = {
     vehicle_type_id: 62,
     note: "Testing - API Default Fragile item that needs good care Welcome.",
     time_type: "schedule",
     pickup_time: "2016-05-13T09:51:16+07:00",
     job_order_number: "66666",
     locations: [
       {
         address:
           tDate +
             "Jl. Sultan Iskandar Muda No.21, Arteri Pondok Indah, Pd. Pinang, Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
         latitude: -6.2608232,
         longitude: 106.7884168,
         recipient_name: "Duke",
         recipient_phone: "+84903398399",
         note: "Second floor, room 609"
       },
       {
         address:
           tDate +
             "Gedung Inti Sentra, Jl. Taman Kemang, RT.14/RW.1, Bangka, Mampang Prpt., Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
         latitude: -6.2608232,
         longitude: 106.7884168,
         recipient_name: "Nam",
         recipient_phone: "+84903856534",
         note: "First floor, right room.",
         need_cod: true,
         cod_note: "You need to get money from Nam",
         cod_invoice_fees: 5000,
         need_pod: true,
         pod_note: "You need to ..."
       }
     ]
   }
    begin
      @rs = deliveree.deliveries_post(delivery)
    rescue Deliveree::ApiError => e
      puts "exception #{e}"
    end
</code></pre>
  </div>

</div>

SDK_ruby/sample-project/Sample_SDK_testing/app/views/deliveree/get_quotes.html.erb
<hr/>
<div class="row">
  <div class="col-lg-12">
    <div class="header">
      <h2>
        Get Quotes List
      </h2>
    </div>
  </div>
  <div class="col-lg-6">
    <table class="table">
      <tr>
        <td>Vehicle type ID</td>
        <td>Name</td>
        <td>Total Fees</td>
        <td>Currency</td>
      </tr>
      <% if @result.present? %>
        <%
          @result.data.each do |result|
        %>
          <tr>
            <td>
              <%=result.vehicle_type_id %>
            </td>
            <td>
              <%=result.vehicle_type_name %>
            </td>
            <td>
              <%=result.total_fees %>
            </td>
            <td>
              <%=result.currency %>
            </td>
          </tr>
        <%end %>
      <%else %>
        <tr>
          <td colspan="4"><%=@error %></td>
        </tr>
      <%end %>
    </table>

  </div>
  <div class="col-lg-6 code">
  <pre><code>
    deliveree = Deliveree::DelivereeApi.new
    location = {
      address:
        "Jl. Sultan Iskandar Muda No.21, Arteri Pondok Indah, Pd. Pinang, Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta, Indonesia",
      latitude: -6.2608232,
      longitude: 106.7884168
    }

    body = Deliveree::Quote.new({time_type: "now", locations: [Deliveree::Location.new( location)]})

    begin
      @result = deliveree.deliveries_get_quote(body)
    rescue Deliveree::ApiError => e
      puts "exception #{e}"
    end
</code></pre>
  </div>

</div>

SDK_ruby/sample-project/Sample_SDK_testing/app/views/deliveree/index.html.erb
<div class="title-head">
  <h2>
    Welcome to the Ruby SDK Dashboard
  </h2>
  <span>
    Please click on menu items to get a details SDK API
  </span>
</div>

SDK_ruby/sample-project/Sample_SDK_testing/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
  <div class="header">
    <img src="https://webapp.sandbox.deliveree.com/assets/Logo_Deliveree_White-d827ebead28b15f9a3ef88d08086fa15.svg" class="rounded mx-auto d-block logo">
  </div>
  <div class="menu">
    <ul class="nav">
      <li class="nav-item">
        <%= link_to "Get Quote", deliveree_get_quotes_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create Booking Delivery", deliveree_create_booking_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Cancel Booking", deliveree_cancel_booking_url, class: "nav-link" %>
      </li>
    </ul>
  </div>
  <div class="title-head">
    <h2> Ruby SDK Example</h2>
  </div>

  <%= yield %>

  <div class="fixed-bottom">
    <div class="footer text-center">
      Copyright by Deliveree Team
    </div>

  </div>
</body>
</html>